/*
 Navicat Premium Data Transfer

 Source Server         : unspman
 Source Server Type    : MySQL
 Source Server Version : 80032 (8.0.32)
 Source Host           : localhost:3306
 Source Schema         : player

 Target Server Type    : MySQL
 Target Server Version : 80032 (8.0.32)
 File Encoding         : 65001

 Date: 20/03/2023 21:56:17
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for video_tag
-- ----------------------------
DROP TABLE IF EXISTS `video_tag`;
CREATE TABLE `video_tag`  (
  `id` int UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `video_id` int UNSIGNED NULL DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE,
  INDEX `fk_video_id_2`(`video_id` ASC) USING BTREE,
  CONSTRAINT `fk_video_id_2` FOREIGN KEY (`video_id`) REFERENCES `video` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE = InnoDB AUTO_INCREMENT = 338 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of video_tag
-- ----------------------------
INSERT INTO `video_tag` VALUES (1, '搞笑,热血,奇幻', 1);
INSERT INTO `video_tag` VALUES (2, '搞笑,冒险,亲子', 2);
INSERT INTO `video_tag` VALUES (3, 'Unknown', 3);
INSERT INTO `video_tag` VALUES (4, '动画', 4);
INSERT INTO `video_tag` VALUES (5, '动作,动画,奇幻', 5);
INSERT INTO `video_tag` VALUES (6, '战斗,科幻,冒险', 6);
INSERT INTO `video_tag` VALUES (7, 'Unknown', 7);
INSERT INTO `video_tag` VALUES (8, '搞笑,亲子', 8);
INSERT INTO `video_tag` VALUES (9, '奇幻,校园,百合,运动,魔法', 9);
INSERT INTO `video_tag` VALUES (10, '动作,动画,奇幻', 10);
INSERT INTO `video_tag` VALUES (11, '战斗,科幻,奇幻,冒险', 11);
INSERT INTO `video_tag` VALUES (12, '科幻', 12);
INSERT INTO `video_tag` VALUES (13, 'Unknown', 13);
INSERT INTO `video_tag` VALUES (14, '动画', 14);
INSERT INTO `video_tag` VALUES (15, '搞笑,亲子', 15);
INSERT INTO `video_tag` VALUES (16, '搞笑,亲子', 16);
INSERT INTO `video_tag` VALUES (17, '奇幻,冒险,治愈', 17);
INSERT INTO `video_tag` VALUES (18, '搞笑,治愈,冒险', 18);
INSERT INTO `video_tag` VALUES (19, '搞笑,恋爱,校园,萝莉', 19);
INSERT INTO `video_tag` VALUES (20, '搞笑,奇幻,亲子,冒险', 20);
INSERT INTO `video_tag` VALUES (21, 'Unknown', 21);
INSERT INTO `video_tag` VALUES (22, '搞笑', 22);
INSERT INTO `video_tag` VALUES (23, '动作,动画,奇幻,剧情', 23);
INSERT INTO `video_tag` VALUES (24, '搞笑,恋爱,校园', 24);
INSERT INTO `video_tag` VALUES (25, '战斗,奇幻,冒险,机战', 25);
INSERT INTO `video_tag` VALUES (26, '亲子', 26);
INSERT INTO `video_tag` VALUES (27, '战斗,科幻,冒险,历史', 27);
INSERT INTO `video_tag` VALUES (28, '搞笑', 28);
INSERT INTO `video_tag` VALUES (29, '动作,动画,科幻,剧情', 29);
INSERT INTO `video_tag` VALUES (30, '搞笑,治愈,亲子', 30);
INSERT INTO `video_tag` VALUES (31, '校园,励志', 31);
INSERT INTO `video_tag` VALUES (32, '搞笑,热血,战斗,奇幻,冒险', 32);
INSERT INTO `video_tag` VALUES (33, 'Unknown', 33);
INSERT INTO `video_tag` VALUES (34, '战斗,科幻', 34);
INSERT INTO `video_tag` VALUES (35, '冒险', 35);
INSERT INTO `video_tag` VALUES (36, 'Unknown', 36);
INSERT INTO `video_tag` VALUES (37, '搞笑,奇幻,青春,美少女', 37);
INSERT INTO `video_tag` VALUES (38, '热血,战斗', 38);
INSERT INTO `video_tag` VALUES (39, '校园,百合', 39);
INSERT INTO `video_tag` VALUES (40, '搞笑,科幻,恋爱,校园,运动,竞技', 40);
INSERT INTO `video_tag` VALUES (41, '搞笑,恋爱,校园', 41);
INSERT INTO `video_tag` VALUES (42, '搞笑,校园', 42);
INSERT INTO `video_tag` VALUES (43, '动作,动画,家庭,奇幻', 43);
INSERT INTO `video_tag` VALUES (44, '竞技', 44);
INSERT INTO `video_tag` VALUES (45, 'Unknown', 45);
INSERT INTO `video_tag` VALUES (46, '喜剧,动画,科幻', 46);
INSERT INTO `video_tag` VALUES (47, '搞笑', 47);
INSERT INTO `video_tag` VALUES (48, 'Unknown', 48);
INSERT INTO `video_tag` VALUES (49, '热血,青春,校园,励志,运动,竞技', 49);
INSERT INTO `video_tag` VALUES (50, 'Unknown', 50);
INSERT INTO `video_tag` VALUES (51, '搞笑,科幻,奇幻,冒险', 51);
INSERT INTO `video_tag` VALUES (52, '搞笑,亲子,冒险', 52);
INSERT INTO `video_tag` VALUES (53, '动画,科幻', 53);
INSERT INTO `video_tag` VALUES (54, '经典', 54);
INSERT INTO `video_tag` VALUES (55, '搞笑,恋爱,校园', 55);
INSERT INTO `video_tag` VALUES (56, '热血,科幻', 56);
INSERT INTO `video_tag` VALUES (57, '热血,战斗,科幻,青春,机战,美少女', 57);
INSERT INTO `video_tag` VALUES (58, '搞笑,美少女', 58);
INSERT INTO `video_tag` VALUES (59, '冒险', 59);
INSERT INTO `video_tag` VALUES (60, '热血,战斗,校园,机战,美少女', 60);
INSERT INTO `video_tag` VALUES (61, '热血,奇幻', 61);
INSERT INTO `video_tag` VALUES (62, '冒险', 62);
INSERT INTO `video_tag` VALUES (63, '搞笑,冒险', 63);
INSERT INTO `video_tag` VALUES (64, '科幻,励志', 64);
INSERT INTO `video_tag` VALUES (65, '推理', 65);
INSERT INTO `video_tag` VALUES (66, '热血,运动', 66);
INSERT INTO `video_tag` VALUES (67, '搞笑,科幻,恋爱,青春', 67);
INSERT INTO `video_tag` VALUES (68, '恋爱,青春', 68);
INSERT INTO `video_tag` VALUES (69, '科幻,奇幻,冒险', 69);
INSERT INTO `video_tag` VALUES (70, 'Unknown', 70);
INSERT INTO `video_tag` VALUES (71, '战斗,科幻,机战', 71);
INSERT INTO `video_tag` VALUES (72, '喜剧,动画,科幻', 72);
INSERT INTO `video_tag` VALUES (73, '搞笑', 73);
INSERT INTO `video_tag` VALUES (74, 'Unknown', 74);
INSERT INTO `video_tag` VALUES (75, '热血,运动,竞技', 75);
INSERT INTO `video_tag` VALUES (76, '搞笑,恋爱', 76);
INSERT INTO `video_tag` VALUES (77, '喜剧,动画', 77);
INSERT INTO `video_tag` VALUES (78, '搞笑,治愈,猎奇', 78);
INSERT INTO `video_tag` VALUES (79, '恋爱', 79);
INSERT INTO `video_tag` VALUES (80, '动画,奇幻,剧情', 80);
INSERT INTO `video_tag` VALUES (81, '恐怖,动画', 81);
INSERT INTO `video_tag` VALUES (82, '青春', 82);
INSERT INTO `video_tag` VALUES (83, '战斗,科幻,奇幻,冒险,运动', 83);
INSERT INTO `video_tag` VALUES (84, '冒险', 84);
INSERT INTO `video_tag` VALUES (85, '热血,励志,战斗', 85);
INSERT INTO `video_tag` VALUES (86, '科幻', 86);
INSERT INTO `video_tag` VALUES (87, '热血,战斗,科幻', 87);
INSERT INTO `video_tag` VALUES (88, '搞笑', 88);
INSERT INTO `video_tag` VALUES (89, '热血,战斗,冒险,励志', 89);
INSERT INTO `video_tag` VALUES (90, 'Unknown', 90);
INSERT INTO `video_tag` VALUES (91, '搞笑,奇幻,冒险,校园,魔法', 91);
INSERT INTO `video_tag` VALUES (92, '搞笑,奇幻,恋爱,后宫', 92);
INSERT INTO `video_tag` VALUES (93, '冒险,热血,亲子', 93);
INSERT INTO `video_tag` VALUES (94, '搞笑', 94);
INSERT INTO `video_tag` VALUES (95, '热血,冒险,励志', 95);
INSERT INTO `video_tag` VALUES (96, '喜剧,动画,奇幻,剧情', 96);
INSERT INTO `video_tag` VALUES (97, '悬疑', 97);
INSERT INTO `video_tag` VALUES (98, '搞笑,亲子', 98);
INSERT INTO `video_tag` VALUES (99, 'Unknown', 99);
INSERT INTO `video_tag` VALUES (100, 'Unknown', 100);
INSERT INTO `video_tag` VALUES (101, '励志', 101);
INSERT INTO `video_tag` VALUES (102, '动画,奇幻', 102);
INSERT INTO `video_tag` VALUES (103, '热血,科幻,奇幻,冒险,励志,竞技', 103);
INSERT INTO `video_tag` VALUES (104, '搞笑', 104);
INSERT INTO `video_tag` VALUES (105, '奇幻,冒险', 105);
INSERT INTO `video_tag` VALUES (106, '战斗,恋爱,校园,推理', 106);
INSERT INTO `video_tag` VALUES (107, '爱情,科幻,剧情', 107);
INSERT INTO `video_tag` VALUES (108, 'Unknown', 108);
INSERT INTO `video_tag` VALUES (109, '搞笑', 109);
INSERT INTO `video_tag` VALUES (110, '奇幻,恋爱', 110);
INSERT INTO `video_tag` VALUES (111, 'Unknown', 111);
INSERT INTO `video_tag` VALUES (112, '搞笑', 112);
INSERT INTO `video_tag` VALUES (113, '恋爱', 113);
INSERT INTO `video_tag` VALUES (114, 'Unknown', 114);
INSERT INTO `video_tag` VALUES (115, '搞笑', 115);
INSERT INTO `video_tag` VALUES (116, '搞笑', 116);
INSERT INTO `video_tag` VALUES (117, '热血,战斗,冒险,运动,竞技', 117);
INSERT INTO `video_tag` VALUES (118, '搞笑', 118);
INSERT INTO `video_tag` VALUES (119, '搞笑,科幻,奇幻,冒险,治愈', 119);
INSERT INTO `video_tag` VALUES (120, 'Unknown', 120);
INSERT INTO `video_tag` VALUES (121, 'Unknown', 121);
INSERT INTO `video_tag` VALUES (122, '动作,犯罪', 122);
INSERT INTO `video_tag` VALUES (123, '历史', 123);
INSERT INTO `video_tag` VALUES (124, '校园', 124);
INSERT INTO `video_tag` VALUES (125, 'Unknown', 125);
INSERT INTO `video_tag` VALUES (126, '亲子', 126);
INSERT INTO `video_tag` VALUES (127, '热血,冒险,科幻', 127);
INSERT INTO `video_tag` VALUES (128, '搞笑,科幻,奇幻,冒险', 128);
INSERT INTO `video_tag` VALUES (129, '冒险,推理', 129);
INSERT INTO `video_tag` VALUES (130, '爱情,喜剧,剧情', 130);
INSERT INTO `video_tag` VALUES (131, '热血,战斗,科幻,青春,催泪,猎奇,机战,美少女', 131);
INSERT INTO `video_tag` VALUES (132, '搞笑,科幻,亲子', 132);
INSERT INTO `video_tag` VALUES (133, '喜剧,罪案,剧情', 133);
INSERT INTO `video_tag` VALUES (134, '科幻,冒险,推理', 134);
INSERT INTO `video_tag` VALUES (135, '恋爱,校园', 135);
INSERT INTO `video_tag` VALUES (136, '搞笑', 136);
INSERT INTO `video_tag` VALUES (137, '搞笑,热血,奇幻,冒险', 137);
INSERT INTO `video_tag` VALUES (138, 'Unknown', 138);
INSERT INTO `video_tag` VALUES (139, 'Unknown', 139);
INSERT INTO `video_tag` VALUES (140, '热血,冒险', 140);
INSERT INTO `video_tag` VALUES (141, '亲子', 141);
INSERT INTO `video_tag` VALUES (142, '热血,战斗,科幻,猎奇,推理', 142);
INSERT INTO `video_tag` VALUES (143, '冒险,恋爱,校园', 143);
INSERT INTO `video_tag` VALUES (144, '搞笑,冒险,校园', 144);
INSERT INTO `video_tag` VALUES (145, '喜剧,罪案,剧情', 145);
INSERT INTO `video_tag` VALUES (146, '喜剧', 146);
INSERT INTO `video_tag` VALUES (147, '恋爱,青春,校园,励志,美少女', 147);
INSERT INTO `video_tag` VALUES (148, '科幻,奇幻,冒险', 148);
INSERT INTO `video_tag` VALUES (149, '动画', 149);
INSERT INTO `video_tag` VALUES (150, '战斗,奇幻,后宫', 150);
INSERT INTO `video_tag` VALUES (151, '冒险', 151);
INSERT INTO `video_tag` VALUES (152, '搞笑', 152);
INSERT INTO `video_tag` VALUES (153, '搞笑,亲子', 153);
INSERT INTO `video_tag` VALUES (154, '搞笑,科幻,奇幻,治愈', 154);
INSERT INTO `video_tag` VALUES (155, '机战,科幻', 155);
INSERT INTO `video_tag` VALUES (156, '冒险,后宫', 156);
INSERT INTO `video_tag` VALUES (157, '励志,历史', 157);
INSERT INTO `video_tag` VALUES (158, '亲子', 158);
INSERT INTO `video_tag` VALUES (159, '热血,战斗,冒险,恋爱', 159);
INSERT INTO `video_tag` VALUES (160, '热血,冒险,历史', 160);
INSERT INTO `video_tag` VALUES (161, '科幻', 161);
INSERT INTO `video_tag` VALUES (162, '青春,校园,励志,运动,竞技', 162);
INSERT INTO `video_tag` VALUES (163, '热血,竞技', 163);
INSERT INTO `video_tag` VALUES (164, '搞笑', 164);
INSERT INTO `video_tag` VALUES (165, '冒险', 165);
INSERT INTO `video_tag` VALUES (166, '热血', 166);
INSERT INTO `video_tag` VALUES (167, 'Unknown', 167);
INSERT INTO `video_tag` VALUES (168, '搞笑,热血,战斗,冒险,校园,美少女', 168);
INSERT INTO `video_tag` VALUES (169, '校园', 169);
INSERT INTO `video_tag` VALUES (170, '恋爱', 170);
INSERT INTO `video_tag` VALUES (171, '热血,科幻,推理', 171);
INSERT INTO `video_tag` VALUES (172, '亲子', 172);
INSERT INTO `video_tag` VALUES (173, '搞笑', 173);
INSERT INTO `video_tag` VALUES (174, '搞笑', 174);
INSERT INTO `video_tag` VALUES (175, '经典,热血,战斗,运动,竞技', 175);
INSERT INTO `video_tag` VALUES (176, 'Unknown', 176);
INSERT INTO `video_tag` VALUES (177, 'Unknown', 177);
INSERT INTO `video_tag` VALUES (178, '冒险', 178);
INSERT INTO `video_tag` VALUES (179, '热血,战斗,奇幻', 179);
INSERT INTO `video_tag` VALUES (180, '搞笑,经典', 180);
INSERT INTO `video_tag` VALUES (181, '搞笑,校园', 181);
INSERT INTO `video_tag` VALUES (182, '搞笑,魔法', 182);
INSERT INTO `video_tag` VALUES (183, '战斗,奇幻,冒险,后宫,校园,百合,魔法,美少女', 183);
INSERT INTO `video_tag` VALUES (184, '搞笑,冒险,励志', 184);
INSERT INTO `video_tag` VALUES (185, '搞笑,青春,恋爱', 185);
INSERT INTO `video_tag` VALUES (186, '冒险', 186);
INSERT INTO `video_tag` VALUES (187, '动作,动画,奇幻', 187);
INSERT INTO `video_tag` VALUES (188, '喜剧,动画,家庭,奇幻,科幻,剧情', 188);
INSERT INTO `video_tag` VALUES (189, 'Unknown', 189);
INSERT INTO `video_tag` VALUES (190, '热血,战斗,奇幻', 190);
INSERT INTO `video_tag` VALUES (191, 'Unknown', 191);
INSERT INTO `video_tag` VALUES (192, '搞笑,战斗,奇幻,魔法', 192);
INSERT INTO `video_tag` VALUES (193, '喜剧,动画,奇幻', 193);
INSERT INTO `video_tag` VALUES (194, '喜剧,剧情,奇幻', 194);
INSERT INTO `video_tag` VALUES (195, '搞笑,恋爱,青春,励志', 195);
INSERT INTO `video_tag` VALUES (196, 'Unknown', 196);
INSERT INTO `video_tag` VALUES (197, '战斗,奇幻,冒险,治愈', 197);
INSERT INTO `video_tag` VALUES (198, 'Unknown', 198);
INSERT INTO `video_tag` VALUES (199, '动作,动画,奇幻', 199);
INSERT INTO `video_tag` VALUES (200, '搞笑', 200);
INSERT INTO `video_tag` VALUES (201, '搞笑', 201);
INSERT INTO `video_tag` VALUES (202, '搞笑', 202);
INSERT INTO `video_tag` VALUES (203, '搞笑,经典,热血,战斗,奇幻,恋爱,催泪', 203);
INSERT INTO `video_tag` VALUES (204, '恋爱,热血,竞技', 204);
INSERT INTO `video_tag` VALUES (205, '喜剧', 205);
INSERT INTO `video_tag` VALUES (206, '亲子', 206);
INSERT INTO `video_tag` VALUES (207, '搞笑,青春,校园', 207);
INSERT INTO `video_tag` VALUES (208, '科幻', 208);
INSERT INTO `video_tag` VALUES (209, '热血,机战,冒险', 209);
INSERT INTO `video_tag` VALUES (210, '科幻', 210);
INSERT INTO `video_tag` VALUES (211, 'Unknown', 211);
INSERT INTO `video_tag` VALUES (212, '搞笑,奇幻,冒险', 212);
INSERT INTO `video_tag` VALUES (213, '搞笑,冒险', 213);
INSERT INTO `video_tag` VALUES (214, '喜剧,剧情', 214);
INSERT INTO `video_tag` VALUES (215, 'Unknown', 215);
INSERT INTO `video_tag` VALUES (216, '冒险', 216);
INSERT INTO `video_tag` VALUES (217, 'Unknown', 217);
INSERT INTO `video_tag` VALUES (218, 'Unknown', 218);
INSERT INTO `video_tag` VALUES (219, '科幻,奇幻,冒险', 219);
INSERT INTO `video_tag` VALUES (220, 'Unknown', 220);
INSERT INTO `video_tag` VALUES (221, '搞笑,亲子', 221);
INSERT INTO `video_tag` VALUES (222, '搞笑,经典,科幻,青春,励志', 222);
INSERT INTO `video_tag` VALUES (223, '热血', 223);
INSERT INTO `video_tag` VALUES (224, '亲子', 224);
INSERT INTO `video_tag` VALUES (225, 'Unknown', 225);
INSERT INTO `video_tag` VALUES (226, '冒险', 226);
INSERT INTO `video_tag` VALUES (227, '励志,历史', 227);
INSERT INTO `video_tag` VALUES (228, 'Unknown', 228);
INSERT INTO `video_tag` VALUES (229, 'Unknown', 229);
INSERT INTO `video_tag` VALUES (230, 'Unknown', 230);
INSERT INTO `video_tag` VALUES (231, '亲子,冒险', 231);
INSERT INTO `video_tag` VALUES (232, '恋爱', 232);
INSERT INTO `video_tag` VALUES (233, '搞笑,奇幻,后宫,治愈', 233);
INSERT INTO `video_tag` VALUES (234, 'Unknown', 234);
INSERT INTO `video_tag` VALUES (235, '治愈,励志,青春', 235);
INSERT INTO `video_tag` VALUES (236, 'Unknown', 236);
INSERT INTO `video_tag` VALUES (237, '热血,战斗,奇幻,历史', 237);
INSERT INTO `video_tag` VALUES (238, '恐怖,剧情', 238);
INSERT INTO `video_tag` VALUES (239, 'Unknown', 239);
INSERT INTO `video_tag` VALUES (240, '美食', 240);
INSERT INTO `video_tag` VALUES (241, '搞笑,励志,科幻', 241);
INSERT INTO `video_tag` VALUES (242, '搞笑,恋爱,校园', 242);
INSERT INTO `video_tag` VALUES (243, '冒险,机战', 243);
INSERT INTO `video_tag` VALUES (244, '搞笑,恋爱,校园', 244);
INSERT INTO `video_tag` VALUES (245, '搞笑', 245);
INSERT INTO `video_tag` VALUES (246, '科幻,冒险,机战', 246);
INSERT INTO `video_tag` VALUES (247, '冒险', 247);
INSERT INTO `video_tag` VALUES (248, '搞笑', 248);
INSERT INTO `video_tag` VALUES (249, '热血,励志', 249);
INSERT INTO `video_tag` VALUES (250, '战斗,冒险,恋爱', 250);
INSERT INTO `video_tag` VALUES (251, '热血,科幻,催泪,机战', 251);
INSERT INTO `video_tag` VALUES (252, '搞笑,历史', 252);
INSERT INTO `video_tag` VALUES (253, '动画,青春,剧情', 253);
INSERT INTO `video_tag` VALUES (254, '战斗,冒险,校园', 254);
INSERT INTO `video_tag` VALUES (255, '搞笑,恋爱,冒险', 255);
INSERT INTO `video_tag` VALUES (256, '热血', 256);
INSERT INTO `video_tag` VALUES (257, '冒险', 257);
INSERT INTO `video_tag` VALUES (258, '搞笑,奇幻,冒险,恋爱', 258);
INSERT INTO `video_tag` VALUES (259, '冒险', 259);
INSERT INTO `video_tag` VALUES (260, '爱情,剧情', 260);
INSERT INTO `video_tag` VALUES (261, '治愈,亲子', 261);
INSERT INTO `video_tag` VALUES (262, '爱情,动画', 262);
INSERT INTO `video_tag` VALUES (263, '冒险', 263);
INSERT INTO `video_tag` VALUES (264, '冒险,科幻', 264);
INSERT INTO `video_tag` VALUES (265, '运动', 265);
INSERT INTO `video_tag` VALUES (266, '励志', 266);
INSERT INTO `video_tag` VALUES (267, '魔法,美少女', 267);
INSERT INTO `video_tag` VALUES (268, '搞笑', 268);
INSERT INTO `video_tag` VALUES (269, '战斗,励志', 269);
INSERT INTO `video_tag` VALUES (270, '搞笑,青春,校园', 270);
INSERT INTO `video_tag` VALUES (271, '搞笑,校园', 271);
INSERT INTO `video_tag` VALUES (272, '冒险', 272);
INSERT INTO `video_tag` VALUES (273, '恋爱,校园', 273);
INSERT INTO `video_tag` VALUES (274, 'Unknown', 274);
INSERT INTO `video_tag` VALUES (275, 'Unknown', 275);
INSERT INTO `video_tag` VALUES (276, '推理', 276);
INSERT INTO `video_tag` VALUES (277, 'Unknown', 277);
INSERT INTO `video_tag` VALUES (278, '搞笑,科幻,恋爱,校园,萝莉', 278);
INSERT INTO `video_tag` VALUES (279, '搞笑,奇幻,恋爱', 279);
INSERT INTO `video_tag` VALUES (280, '奇幻,恋爱,校园,萝莉', 280);
INSERT INTO `video_tag` VALUES (281, '搞笑,校园,美少女,萝莉,亲子', 281);
INSERT INTO `video_tag` VALUES (282, '战斗,奇幻,恋爱,青春,催泪,机战,历史,美少女', 282);
INSERT INTO `video_tag` VALUES (283, '历史', 283);
INSERT INTO `video_tag` VALUES (284, '搞笑', 284);
INSERT INTO `video_tag` VALUES (285, '恋爱,青春,校园', 285);
INSERT INTO `video_tag` VALUES (286, '战斗,科幻,恋爱,励志', 286);
INSERT INTO `video_tag` VALUES (287, '热血,科幻,机战', 287);
INSERT INTO `video_tag` VALUES (288, 'Unknown', 288);
INSERT INTO `video_tag` VALUES (289, '搞笑,励志,亲子', 289);
INSERT INTO `video_tag` VALUES (290, '战斗,冒险,励志', 290);
INSERT INTO `video_tag` VALUES (291, 'Unknown', 291);
INSERT INTO `video_tag` VALUES (292, '亲子', 292);
INSERT INTO `video_tag` VALUES (293, '热血,科幻,青春,校园,运动,竞技', 293);
INSERT INTO `video_tag` VALUES (294, '搞笑,科幻,亲子', 294);
INSERT INTO `video_tag` VALUES (295, '战斗,科幻,奇幻,冒险', 295);
INSERT INTO `video_tag` VALUES (296, '亲子', 296);
INSERT INTO `video_tag` VALUES (297, '搞笑,恋爱', 297);
INSERT INTO `video_tag` VALUES (298, '搞笑,励志', 298);
INSERT INTO `video_tag` VALUES (299, '战斗,科幻,奇幻,催泪,治愈,美少女,萝莉', 299);
INSERT INTO `video_tag` VALUES (300, '励志,亲子,冒险', 300);
INSERT INTO `video_tag` VALUES (301, '搞笑,亲子', 301);
INSERT INTO `video_tag` VALUES (302, 'Unknown', 302);
INSERT INTO `video_tag` VALUES (303, '励志', 303);
INSERT INTO `video_tag` VALUES (304, '科幻', 304);
INSERT INTO `video_tag` VALUES (305, '热血,运动', 305);
INSERT INTO `video_tag` VALUES (306, 'Unknown', 306);
INSERT INTO `video_tag` VALUES (307, '搞笑,恋爱,后宫,校园,魔法', 307);
INSERT INTO `video_tag` VALUES (308, '罪案,剧情', 308);
INSERT INTO `video_tag` VALUES (309, '搞笑,恋爱,青春,校园', 309);
INSERT INTO `video_tag` VALUES (310, '奇幻,冒险', 310);
INSERT INTO `video_tag` VALUES (311, '冒险,恋爱', 311);
INSERT INTO `video_tag` VALUES (312, 'Unknown', 312);
INSERT INTO `video_tag` VALUES (313, '剧情', 313);
INSERT INTO `video_tag` VALUES (314, '搞笑', 314);
INSERT INTO `video_tag` VALUES (315, '热血,运动', 315);
INSERT INTO `video_tag` VALUES (316, '亲子,历史', 316);
INSERT INTO `video_tag` VALUES (317, '奇幻,恋爱', 317);
INSERT INTO `video_tag` VALUES (318, 'Unknown', 318);
INSERT INTO `video_tag` VALUES (319, 'Unknown', 319);
INSERT INTO `video_tag` VALUES (320, 'Unknown', 320);
INSERT INTO `video_tag` VALUES (321, '机战', 321);
INSERT INTO `video_tag` VALUES (322, '搞笑,亲子', 322);
INSERT INTO `video_tag` VALUES (323, '治愈,百合,运动', 323);
INSERT INTO `video_tag` VALUES (324, '科幻,冒险,推理', 324);
INSERT INTO `video_tag` VALUES (325, '动画,科幻', 325);
INSERT INTO `video_tag` VALUES (326, '科幻,奇幻,恋爱,校园,推理', 327);
INSERT INTO `video_tag` VALUES (327, '搞笑,奇幻,校园', 328);
INSERT INTO `video_tag` VALUES (328, '搞笑,热血', 329);
INSERT INTO `video_tag` VALUES (329, 'Unknown', 330);
INSERT INTO `video_tag` VALUES (330, '搞笑,亲子', 331);
INSERT INTO `video_tag` VALUES (331, '战斗,奇幻,冒险,校园,美少女', 332);
INSERT INTO `video_tag` VALUES (332, '搞笑,校园', 333);
INSERT INTO `video_tag` VALUES (333, '热血,战斗,奇幻,冒险,励志', 334);
INSERT INTO `video_tag` VALUES (334, '亲子', 335);
INSERT INTO `video_tag` VALUES (335, '亲子,冒险', 336);
INSERT INTO `video_tag` VALUES (336, '搞笑,奇幻,冒险', 337);
INSERT INTO `video_tag` VALUES (337, 'Unknown', 338);

SET FOREIGN_KEY_CHECKS = 1;
